name: someAction

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: 
      - master
env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
  
jobs:
  someAction:
    runs-on: ubuntu-latest

    steps:
    
      - name: Extract branch name
        run: echo "PR_Branch_Name=${{ github.head_ref }}" >> $GITHUB_ENV  

      - name: Validate Title
        run: |
              echo PR Numer is: $GITHUB_PR_NUMBER
                
              restApiPRTitle=$(curl \
                                      -H "Accept: application/vnd.github.v3+json" \
                                      https://api.github.com/repos/naregkar/repo2/pulls/$GITHUB_PR_NUMBER | jq  -r '.title')
                
              echo $restApiPRTitle
              
              if [[ $restApiPRTitle =~ ^\[DT-[0-9]+\] ]]; then
                echo 'PR Title is in correct format.'
              else
                echo 'PR Title does not comply with the required pattern.'                  
                  exit 1
              fi
